services:
  - type: web
    name: gpt-researcher-dentistry
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: LITELLM_PROXY_URL
        value: https://llm.rbnk.uk
      - key: LITELLM_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: RESEARCH_SERVICE_AUTH_TOKEN
        generateValue: true
      - key: FAST_LLM_MODEL
        value: o4-mini
      - key: SMART_LLM_MODEL
        value: o4
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: FRONTEND_URL
        value: https://dentistry-explained.vercel.app